CREATE TABLE IF NOT EXISTS address(
   id      VARCHAR(256) NOT NULL PRIMARY KEY
  ,city    VARCHAR(256) NOT NULL
  ,country VARCHAR(256) NOT NULL
  ,pincode VARCHAR(256) NOT NULL
);
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-1','Marogong','MY','257718');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-2','Adar','SG','573478');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-3','Medan','PH','165841');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-4','Río Grande','PH','481285');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-5','Kupu','US','304180');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-6','Achanizo','US','300467');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-7','Bang Pahan','UK','641993');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-8','Ventanas','PH','454830');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-9','Siemianowice Śląskie','US','482326');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-10','Zhaoguli','TH','394034');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-11','Goiás','TH','609163');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-12','Sukarame','US','169003');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-13','Feričanci','ID','134008');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-14','Gyangkar','CN','598801');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-15','Kaparéllion','TH','265709');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-16','Jambulang','MY','146745');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-17','Oslo','MY','627923');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-18','Mojoroto','TH','436094');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-19','Huage','US','529192');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-20','Dayin','PH','558118');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-21','El Águila','TH','346837');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-22','Al Majd','SG','331198');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-23','Cucutilla','SG','254080');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-24','Beloeil','CN','457227');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-25','Telukpakedai','CN','542256');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-26','Pingdu','MY','605734');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-27','Pongkor','PH','244487');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-28','Huimin','PH','221123');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-29','Qiting','US','442043');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-30','Amagarapati','UK','222055');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-31','Cimuncang','PH','356773');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-32','Kano','US','235980');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-33','Kari','PH','261931');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-34','Taiping','PH','320821');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-35','Yanjiatai','PH','623494');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-36','Carlsbad','TH','645743');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-37','Dongxiang','MY','328700');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-38','Islāmkot','PH','109326');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-39','Dadong','CN','510473');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-40','Pira','TH','548587');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-41','Dzaoudzi','SG','512647');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-42','Bungsuan','TH','478155');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-43','Mulawato','TH','342119');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-44','Salavat','US','594368');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-45','Lawonda','PH','184619');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-46','Zaječí','TH','418908');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-47','Chodów','SG','394080');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-48','Baishui','TH','189451');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-49','San Jose','UK','445653');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-50','Jitian','CN','153721');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-51','Fundación','SG','190757');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-52','El Fureidīs','CN','229322');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-53','Marićka','MY','530587');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-54','Iwierzyce','US','330384');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-55','Banga','MY','371670');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-56','Oslo','PH','243636');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-57','Bielefeld','SG','156428');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-58','Ziroudani','MY','348552');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-59','Murça','UK','252329');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-60','Zhireken','TH','416262');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-61','West Kelowna','UK','449352');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-62','Domont','ID','368183');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-63','R S','CN','638988');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-64','Baini','ID','405684');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-65','Nanjing','UK','665159');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-66','Padhahegha','PH','256405');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-67','Pantai','SG','656809');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-68','Kuantan','ID','650315');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-69','Baratleke','PH','198118');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-70','San Ramon','SG','435586');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-71','Waterloo','TH','342371');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-72','Jiangyan','US','586965');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-73','Londiani','UK','225294');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-74','Néa Filadélfeia','ID','478268');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-75','Corredoura','UK','157470');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-76','Nantes','CN','251347');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-77','Madimba','US','363050');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-78','Jiaoqi','US','152756');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-79','Tiandian','PH','618745');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-80','Washington','TH','476252');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-81','Almargem do Bispo','CN','262745');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-82','Naples','TH','131532');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-83','Xiacang','SG','303839');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-84','Sepanjang','ID','310409');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-85','Datagon','SG','216352');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-86','Cireundang','UK','278186');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-87','Batasan','ID','488188');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-88','Crossfield','CN','378696');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-89','Narimanov','TH','292254');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-90','Birmingham','US','477593');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-91','Paitan Este','TH','321513');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-92','Byera Village','SG','215197');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-93','Kurunegala','SG','212334');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-94','Emiliano Zapata','TH','546623');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-95','Tarikolot','ID','285193');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-96','Camagüey','TH','202144');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-97','Cisaro','UK','227827');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-98','Ballymun','MY','595583');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-99','Springfield','TH','624156');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-100','Atsipópoulon','CN','293657');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-101','Zavoronezhskoye','PH','513960');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-102','Kulutan','TH','495618');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-103','Starodub','TH','363079');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-104','Dunyāpur','TH','286277');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-105','Örebro','TH','170431');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-106','Décines-Charpieu','PH','401210');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-107','Jindong','US','602410');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-108','Garunggang','SG','129501');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-109','Karangsumber','SG','366486');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-110','Huanoquite','US','422096');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-111','Mumias','US','456957');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-112','Sukakarya','SG','592913');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-113','Driyorejo','TH','272857');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-114','Turiys’k','UK','128151');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-115','Pingding','PH','186807');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-116','Banatsko Karađorđevo','MY','333953');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-117','Sujiazhuang','PH','555986');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-118','Domoni','US','208827');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-119','Garbolovo','PH','106290');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-120','San Antonio','CN','515421');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-121','Lākshām','SG','401015');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-122','Aguada de Pasajeros','CN','176554');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-123','Sindangbarang','UK','251600');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-124','Vityazevo','PH','555231');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-125','Longjin','CN','514456');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-126','Gandara','MY','642128');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-127','Dapchi','TH','332703');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-128','Sarlat-la-Canéda','MY','254819');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-129','Granard','SG','461355');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-130','Salogon','TH','644956');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-131','Sacramento','US','513558');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-132','Novokuybyshevsk','US','553795');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-133','Zliv','CN','499343');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-134','Semiluki','CN','529646');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-135','Eiriz','PH','142847');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-136','Pianling','CN','199674');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-137','Laventille','US','139551');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-138','Paris 12','MY','520676');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-139','Beltinci','SG','355952');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-140','Zator','TH','158075');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-141','Bhimbar','ID','473610');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-142','Criação Velha','MY','629431');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-143','Décines-Charpieu','PH','657326');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-144','Grosuplje','UK','207747');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-145','London','TH','588223');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-146','Burujul','SG','492472');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-147','Nantes','US','536922');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-148','Foúrnoi','SG','653589');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-149','Guérande','SG','280025');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-150','Changgang','ID','378489');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-151','Iguatu','UK','335653');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-152','Taraan','MY','232181');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-153','Boavista','ID','222367');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-154','Huddinge','SG','590336');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-155','Rantauambacang','CN','621084');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-156','Budagovo','SG','665515');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-157','Mandal','PH','313644');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-158','Huancheng','UK','368222');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-159','Sumberan','SG','597062');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-160','Sovetsk','CN','382636');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-161','Kristiansand S','PH','308478');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-162','Corroios','UK','515749');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-163','Ferreñafe','PH','250076');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-164','Villa Dolores','TH','182981');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-165','Changhua','CN','576911');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-166','Corralillo','MY','193719');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-167','Breda','CN','658796');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-168','Puerto Boyacá','MY','458434');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-169','Lambangan Kulon','SG','538666');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-170','Bergen','SG','175273');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-171','Kulaman','MY','573529');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-172','Oemollo','US','579327');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-173','Maksatikha','UK','133688');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-174','Hörby','US','615555');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-175','Paris 03','SG','623264');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-176','Patrol','MY','492088');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-177','Těšany','SG','493993');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-178','Panyindangan','TH','379588');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-179','Bern','UK','325290');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-180','Mont-Saint-Aignan','UK','448620');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-181','Xarardheere','SG','117531');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-182','Jazovo','TH','201495');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-183','Xiabaishi','UK','594486');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-184','Nacka','UK','204245');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-185','San Rafael','ID','513456');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-186','Manga','MY','320496');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-187','Duobaoshan','CN','484773');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-188','Yangsan','SG','158748');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-189','Fuxing','UK','122236');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-190','La Unión','UK','227699');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-191','Piraí','US','345140');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-192','Shengli','UK','257711');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-193','Cipicung','US','344760');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-194','Cerkvenjak','UK','392377');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-195','Rawson','CN','114083');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-196','Cacocum','ID','371783');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-197','Wuyang','TH','554622');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-198','Zarichne','CN','567688');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-199','Mantalongon','CN','449050');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-200','Hangu','UK','252802');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-201','Raniżów','SG','511092');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-202','Phoenix','MY','515244');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-203','Aix-en-Provence','UK','243162');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-204','Ar Rahad','CN','147646');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-205','Saint-Ouen','CN','607414');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-206','Cidikit Girang','SG','185980');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-207','Karlstad','PH','497602');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-208','Göteborg','TH','446540');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-209','Mqabba','MY','108881');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-210','Löddeköpinge','UK','472418');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-211','Saint Augustine','MY','383545');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-212','Homa Bay','US','494801');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-213','Kalilangan','TH','440487');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-214','Celso Ramos','ID','164228');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-215','Thị Trấn Mù Cang Chải','CN','484437');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-216','Maputo','UK','282057');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-217','Dukuhmencek Lor','ID','241264');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-218','Shangzhuang','US','131908');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-219','Quebo','TH','563810');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-220','Seydi','MY','423213');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-221','Szeged','SG','446228');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-222','Maochen','PH','361800');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-223','Horqueta','MY','562655');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-224','Luján de Cuyo','UK','635957');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-225','Naga','UK','202312');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-226','Esso','US','661296');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-227','Semanding','MY','294830');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-228','Sanfang','SG','380630');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-229','Rennebu','ID','281332');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-230','Nghĩa Hành','CN','156506');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-231','Andoany','PH','385577');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-232','Manning','ID','519415');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-233','Karak City','CN','426002');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-234','Pakusari','SG','482553');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-235','Gąbin','SG','205119');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-236','Phu Luang','CN','101875');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-237','Almodôvar','MY','607170');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-238','Novoukrayinka','MY','229565');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-239','Žulová','CN','439425');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-240','Yantan','TH','650705');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-241','Pīr jo Goth','US','606024');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-242','Picoto','PH','204894');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-243','Mendī','ID','548734');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-244','Rongai','UK','455428');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-245','Chatan','ID','240932');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-246','Bailu','TH','154647');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-247','Gakovo','US','108668');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-248','Luče','CN','362938');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-249','Esperanza','US','473762');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-250','Xubao','ID','493197');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-251','Fundong','ID','379272');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-252','Poctol','TH','512863');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-253','Cancela','UK','246205');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-254','Costa Sacate','PH','154628');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-255','Ciparasi','TH','221469');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-256','Unisław','SG','535518');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-257','Mislak','SG','336913');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-258','Ukhta','PH','146466');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-259','Zhangxi','PH','484125');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-260','Stockholm','UK','657225');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-261','A Yun Pa','ID','431608');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-262','Veiga','US','319137');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-263','Jingdang','UK','278431');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-264','Václavovice','MY','548407');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-265','Matelândia','ID','584966');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-266','Basa','CN','122065');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-267','Arraga','US','155772');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-268','Bakuriani','CN','622617');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-269','Korhogo','PH','263796');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-270','Mangero','TH','428923');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-271','Zimovniki','US','657663');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-272','Krugersdorp','UK','207277');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-273','Białogard','CN','633120');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-274','Örbyhus','CN','641789');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-275','Yaqian','CN','110467');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-276','Esfarāyen','CN','513988');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-277','Ponte Nova','UK','129762');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-278','Lipnica','TH','492694');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-279','Vihti','US','516830');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-280','Gedangan','SG','280880');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-281','Xiatang','ID','232346');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-282','Ilha Solteira','US','562110');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-283','Bomomani','CN','613586');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-284','Nampula','ID','604829');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-285','Dumandesa','SG','608527');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-286','Xianqiao','ID','168495');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-287','Tanlin','MY','134755');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-288','Jojoima','CN','118551');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-289','Gesik','PH','210893');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-290','Azun Atme','MY','341539');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-291','P’yŏngsŏng','ID','185241');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-292','Turki','UK','361933');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-293','Magtangol','MY','115457');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-294','Puerto Montt','UK','223073');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-295','Taguing','ID','388869');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-296','Myanaung','TH','233724');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-297','Valašská Bystřice','PH','444726');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-298','Bassila','TH','490447');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-299','Dijon','TH','475924');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-300','Gniechowice','US','661772');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-301','Biscucuy','ID','636902');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-302','Conde','ID','132865');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-303','Tongyangdao','UK','117594');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-304','Cogon','CN','204584');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-305','Qādirpur Rān','MY','630073');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-306','Curridabat','SG','210768');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-307','Guxi','MY','216893');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-308','San Sebastián de Yalí','ID','304594');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-309','Mabini','MY','367018');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-310','Tarragona','ID','491407');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-311','Rāmhormoz','ID','298429');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-312','Beiling','US','167064');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-313','Sapu Padidu','UK','134751');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-314','Matsubase','PH','485348');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-315','Santol','US','175960');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-316','Minneapolis','MY','578422');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-317','Roza','UK','267399');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-318','Skórcz','CN','370674');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-319','Tabālah','CN','462194');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-320','Buzhakan','UK','474263');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-321','Zheyuan','MY','641086');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-322','Bárrio','PH','270495');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-323','Agogo','SG','363006');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-324','Banjar Pasekan','US','352837');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-325','Naga','PH','576327');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-326','Cimara','MY','209144');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-327','Artashat','PH','382036');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-328','Gualmatán','SG','561779');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-329','Duoxiang','US','596598');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-330','Jesús Menéndez','ID','151666');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-331','Kaniv','CN','269088');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-332','Dzików Stary','SG','342156');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-333','Kedungbacin','ID','512320');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-334','Sertolovo','SG','549403');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-335','Del Valle','ID','630040');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-336','Qiancang','UK','352056');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-337','Armash','PH','361988');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-338','San Buenaventura','MY','286772');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-339','Södertälje','US','167618');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-340','Soroti','SG','560207');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-341','Kavadarci','SG','568007');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-342','Besah','PH','461675');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-343','Czarnocin','TH','396219');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-344','Thị Trấn Mường Khến','MY','355580');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-345','San Jose','MY','330657');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-346','Youhao','PH','397125');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-347','Minsk','ID','125331');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-348','Cirahab','CN','522599');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-349','Radziszów','SG','342041');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-350','Sevaster','SG','234150');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-351','Al Wardānīn','CN','161205');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-352','Lanxi','PH','267533');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-353','Morteros','MY','647485');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-354','Lokokrangan','MY','126506');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-355','Myadzyel','US','419726');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-356','Cibaregbeg','UK','208593');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-357','Athens','CN','523103');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-358','Kim Sơn','PH','175481');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-359','Qanliko’l','MY','123317');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-360','Gorgān','ID','576608');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-361','Nowa Sól','PH','265482');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-362','Kinéta','MY','420387');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-363','A’yi Take','MY','324431');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-364','Huayllabamba','PH','364714');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-365','Sangzhen','UK','530309');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-366','Omaha','UK','647086');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-367','Sanxiang','ID','487136');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-368','Sherwood Park','UK','374670');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-369','Novosel’ye','PH','320324');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-370','Mauhao','MY','581990');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-371','‘Anātā','ID','125647');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-372','Donglu','TH','197745');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-373','Sovetskaya Gavan’','MY','249823');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-374','Suzdal’','US','521794');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-375','Ngrowo','US','604180');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-376','Helsingborg','MY','606409');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-377','Uyugan','ID','216333');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-378','Saint-Cloud','PH','346746');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-379','Zamoskvorech’ye','US','458469');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-380','Cinco Saltos','UK','398237');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-381','Radocza','SG','480501');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-382','Áno Kalentíni','TH','314227');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-383','Xingdian','ID','228356');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-384','Atuntaqui','US','202560');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-385','Tsarychanka','PH','365945');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-386','Villaba','TH','534292');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-387','Hualgayoc','UK','553994');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-388','Quchanghī','MY','147828');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-389','Nanxing','MY','593540');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-390','Nantian','CN','214961');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-391','Taounate','PH','466540');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-392','Cishan','SG','524406');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-393','Mandera','CN','361967');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-394','Mauraro','US','123887');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-395','Amarillo','CN','572430');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-396','Beiping','ID','603532');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-397','Tsirang','ID','305771');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-398','Napoli','US','239098');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-399','Kijang','TH','121443');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-400','Tougan','PH','319374');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-401','Sydney','US','247465');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-402','Touzao','PH','292652');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-403','Třinec','PH','257483');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-404','Tuba','UK','656809');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-405','Xianan','MY','189959');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-406','Zamoskvorech’ye','TH','590051');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-407','Oeba','CN','588491');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-408','Gjilan','PH','204140');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-409','Káto Asítai','CN','493046');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-410','San Juan Nepomuceno','SG','322292');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-411','Dar Chabanne','CN','643401');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-412','Río Grande','CN','287916');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-413','Pampa Hermosa','SG','247214');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-414','Kremidivka','UK','360865');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-415','Kruševica','US','555203');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-416','Kozel’shchyna','SG','473595');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-417','Chã','MY','280667');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-418','Nizhniy Chir','US','358769');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-419','Valencia','ID','300623');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-420','Lanta Timur','SG','161326');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-421','Pasar Kidul','SG','304351');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-422','Taobei','TH','384959');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-423','Kalān Deh','ID','440244');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-424','Isoka','CN','428592');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-425','Langchi','CN','276381');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-426','Ebene','SG','330208');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-427','Thị Trấn Phù Yên','US','584009');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-428','Wucun','US','454980');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-429','Salt Lake City','SG','656446');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-430','Mbanza Congo','TH','432007');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-431','Villa Aglipay','US','152578');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-432','Tānsen','MY','624413');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-433','Zhenxing','UK','504994');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-434','Lixi','SG','184040');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-435','Qŭshkŭpir','SG','409944');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-436','Nyima','PH','213872');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-437','Itaguaí','SG','127432');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-438','Ouricuri','TH','129660');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-439','Didian','US','415947');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-440','Bābol','ID','165694');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-441','Aimorés','SG','244325');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-442','Tomari','ID','456713');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-443','Cikarang','UK','211911');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-444','Halong','SG','360508');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-445','Chennevières-sur-Marne','PH','380639');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-446','Boavista','ID','331012');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-447','Bicurga','US','328198');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-448','Guadalupe','ID','550066');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-449','Lutomiersk','SG','391535');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-450','Świętajno','ID','618064');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-451','Fatuhilik','SG','503010');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-452','Belén','SG','633699');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-453','Kambingan','UK','510501');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-454','Göteborg','UK','373100');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-455','Niquelândia','TH','301304');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-456','Sekartaji','PH','210506');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-457','Karamat','ID','389862');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-458','Tanjung Palas','US','217573');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-459','Meixian','PH','349080');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-460','Chadong','PH','378136');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-461','Jedlina-Zdrój','ID','554910');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-462','Xianyang','UK','553124');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-463','Villa del Rosario','US','515638');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-464','Tilmi','UK','430159');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-465','Baykit','PH','442576');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-466','Upi','CN','161947');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-467','Gombang','SG','439504');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-468','Goba','MY','553686');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-469','Sigou','TH','589291');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-470','Złoczew','US','485173');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-471','Cibeureum','TH','661047');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-472','Rio Grande','US','303808');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-473','Doāba','SG','197371');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-474','Lukou','US','593104');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-475','Comapa','CN','139141');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-476','Gennevilliers','CN','607945');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-477','Mayo','SG','248489');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-478','Thị Trấn Vạn Hà','MY','224017');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-479','Basa','SG','610975');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-480','Fendou','MY','196316');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-481','Storuman','US','603124');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-482','Orzu','PH','547579');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-483','Sakurai','MY','274061');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-484','Hamburg Bramfeld','ID','269786');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-485','Waipukang','US','347945');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-486','Leer','UK','238869');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-487','Lutoryż','CN','383858');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-488','El Paso','SG','289472');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-489','Milwaukee','US','415645');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-490','Takehara','UK','165432');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-491','Diaowei','PH','396536');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-492','Cimara','US','311721');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-493','Mirandopólis','CN','332217');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-494','Yangshan','ID','157279');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-495','Makato','SG','414017');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-496','Aix-en-Provence','US','559033');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-497','Liuji','CN','391397');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-498','Eqlīd','PH','422570');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-499','Azogues','ID','237113');
INSERT INTO address(id,city,country,pincode) VALUES ('ADD-500','Al Faḩāḩīl','PH','121445');


-- 77ms